-- Sondages dans la messagerie (question + options + votes + date limite)
-- A exécuter dans le SQL Editor Supabase

CREATE TABLE IF NOT EXISTS polls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  closes_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(message_id)
);

CREATE TABLE IF NOT EXISTS poll_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  position INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS poll_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  option_id BIGINT NOT NULL REFERENCES poll_options(id) ON DELETE CASCADE,
  voter_type TEXT NOT NULL CHECK (voter_type IN ('enseignant', 'eleve')),
  voter_eleve_id TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_poll_votes_unique_voter
ON poll_votes (poll_id, voter_type, COALESCE(voter_eleve_id, '__none__'));

CREATE INDEX IF NOT EXISTS idx_polls_message_id ON polls(message_id);
CREATE INDEX IF NOT EXISTS idx_poll_options_poll_id ON poll_options(poll_id);
CREATE INDEX IF NOT EXISTS idx_poll_votes_poll_id ON poll_votes(poll_id);

ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon insert polls" ON polls;
DROP POLICY IF EXISTS "Allow anon select polls" ON polls;
DROP POLICY IF EXISTS "Allow anon insert poll_options" ON poll_options;
DROP POLICY IF EXISTS "Allow anon select poll_options" ON poll_options;
DROP POLICY IF EXISTS "Allow anon insert poll_votes" ON poll_votes;
DROP POLICY IF EXISTS "Allow anon select poll_votes" ON poll_votes;
DROP POLICY IF EXISTS "Allow anon delete poll_votes" ON poll_votes;

CREATE POLICY "Allow anon insert polls" ON polls FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select polls" ON polls FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert poll_options" ON poll_options FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select poll_options" ON poll_options FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert poll_votes" ON poll_votes FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select poll_votes" ON poll_votes FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon delete poll_votes" ON poll_votes FOR DELETE TO anon USING (true);

GRANT SELECT, INSERT ON public.polls TO anon;
GRANT SELECT, INSERT ON public.poll_options TO anon;
GRANT SELECT, INSERT, DELETE ON public.poll_votes TO anon;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
